//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int Id { get; set; }
        public string Оценка { get; set; }
        public Nullable<int> idПредмета { get; set; }
        public Nullable<int> idСтудента { get; set; }
    
        public virtual Предметы Предметы { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
