//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public Студенты()
        {
            this.Оценки = new HashSet<Оценки>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> idГруппы { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> idРоли { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
